Bookstore: styling
zemola/bookstore pull request #4
Opened 2022-01-21 09:05 UTC by zemola

- Styled the Project to look like the sample given
- Updated my Readme to have the live project hosted on heroku.

2022-01-21 10:12 UTC, hiromataba requested changes
Hi :wave:  @zemola , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### To highlight  :tada: :champagne: 
- No linter errors :heavy_check_mark: 
- Good design :+1: 

## Required Changes ♻️

- [ ] Since this is the bookstore project let us make the README file look more professional by removing the `calculator` information :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150503274-f2d67348-ad73-4ce8-b15b-60e512660764.png)

![image](https://user-images.githubusercontent.com/75126481/150503353-d1dc2bff-beb4-4307-8c46-b4d3d9f6426e.png)

![image](https://user-images.githubusercontent.com/75126481/150503567-63fa6911-5493-48d7-ba5d-daa3cc85c283.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Your live demo does not have the design, fixing it would be better and awesome

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 10:12 UTC, hiromataba commented on src/components/Navbar.js
> +  </div>
- You have a good navigation bar but I think it would be better if we could improve it according to the original design of the project, Kindly fix the `font-family` and the space between the links and the logo 

Your Design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150504005-dcbcd6f5-3c7e-4798-800a-66e568088021.png)

[Zeplin](https://zeplin.io/) Design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150504268-744f6fec-253c-429e-8f34-0113d592fbf0.png)

2022-01-21 10:12 UTC, hiromataba commented on src/components/Book.js
> +        <input className="progress" type="button" value="UPDATE PROGRESS" />
- [ ] Please update this section to match the original design , Your `CURRENT CHAPTER` and `Chapter 17` are to close, Please fix your progress `font-family` and color of `completed`, Kindly fix your `UPDATE PROGRESS` `font-size`

Your Design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150506118-bec38ed3-1c8d-4451-862c-9f1549edb1e5.png)



Zeplin design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150505575-7df572c7-c7e8-4da7-80e8-395d951afa0a.png)

2022-01-21 10:12 UTC, hiromataba commented on src/components/Book.js
>          <article>
- [ ] Please update your Book title `font-size` and `font-family`, the author name `color`, category `color` and `font-weight` according to zeplin design 

Your design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150507906-3fd6a080-65b0-4b0f-826c-ca4bfba33aa5.png)

Zeplin design :point_down: 

![image](https://user-images.githubusercontent.com/75126481/150508260-20612861-5d3a-473c-b98d-936b7c1e709e.png)

2022-01-22 10:36 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hi there 👋🏽 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] There are still some features that the previous reviewer requested that you are yet to implement. Your design is still not exactly like the [zeplin design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378). Highlighted below are the differences between your design and the [zeplin design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378). Kindly take a look at them and make the changes.
- In your design below, the color of ``` Books ``` is the wrong color and the spacing between the nav and the first card is too small.

<img width="1199" alt="Screenshot 2022-01-22 at 11 19 03" src="https://user-images.githubusercontent.com/64774936/150634814-36ec7cb5-2b6d-4a0e-9e16-afa2ace93510.png">

- Also the color of the ``` author name ``` should be the same as ``` comments, remove, edit ```.  Your design is also missing the vertical line between the completed circle and the current progress as highlighted below.

<img width="1094" alt="Screenshot 2022-01-22 at 11 29 14" src="https://user-images.githubusercontent.com/64774936/150634949-50ad5e2e-5748-44ad-bb18-f8ed42953a15.png">

- ### Zeplin design
Kindly take a look at the highlighted areas in the zeplin design as they are what your design currently misses.

<img width="994" alt="Screenshot 2022-01-22 at 11 18 49" src="https://user-images.githubusercontent.com/64774936/150634977-372cb234-6703-4d69-a265-e067f68bba6e.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
- As the previous reviewer mentioned, your live demo does not work well, please fix it as it would make it easier for any recruiter or indidvidual looking at your code to easily see how it looks on the web.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 11:26 UTC, zemola commented
Dear @Ghiftee ,
Looking a the first reviewer, he place all you are pointing out now under optional, which made me feel the need to do that later since time is not on my side, you bringing it up now as a review will jeopardize my chances but it is fine will try to work things out.

2022-01-22 12:50 UTC, sinansevgi commented
> Dear @Ghiftee , Looking a the first reviewer, he place all you are pointing out now under optional, which made me feel the need to do that later since time is not on my side, you bringing it up now as a review will jeopardize my chances but it is fine will try to work things out.

Hi @zemola, I just want to clear this misunderstanding. As stated in the first review, only comments with the `[OPTIONAL]` prefix are optional.

2022-01-22 12:51 UTC, sinansevgi approved these changes
Hi @zemola , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

[Optional]
It will be really cool if you update the live demo to the latest version of your website.
 
Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 13:24 UTC, merged